import pytrf

#seq = "ATTGAATGGAAATGAAAGGGGTCATCATCTAATGGAATCGCATGGAATCATCATCAAATGGAATCGAATGGAATCAACATCAAATGGAATCTAATGGAATCATTGAACGGAATTGAATGGAATCGTCATCGAATGAATTGAATGCAATCATCGAATGGTCTCGAATGGAATCATCTTCAAATGGAATGGAATGGAAT"
#seq = "TCCTCCTCCTCCTCTTTCCATTAAGTT"
#seq = "TGTGTGTGTGTGTGTTTTGTTTTTCAACTTAAAAA"
seq = "AAAAAAAAAAAAAAAAGAAATCCAAATAAAATTT"

atr = pytrf.ATRFinder('chr1', seq)
print(atr.as_list())
