import pytrf

seq = "ATTGAATGGAAATGAAAGGGGTCATCATCTAATGGAATCGCATGGAATCATCATCAAATGGAATCGAATGGAATCAACATCAAATGGAATCTAATGGAATCATTGAACGGAATTGAATGGAATCGTCATCGAATGAATTGAATGCAATCATCGAATGGTCTCGAATGGAATCATCTTCAAATGGAATGGAATGGAAT"
#seq = "TCCTCCTCCTCCTCTTTCCATTAAGTT"

atr = pytrf.ATRFinder('chr1', seq)
print(atr.as_list())
